os: linux
dist: focal
language: generic

git:
  depth: 5

cabal: "3.2"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

addons:
  apt:
    sources:
    - sourceline: "ppa:hvr/ghc"
    packages:
    - ghc-8.6.5
    - ghc-8.8.3
    - ghc-8.10.4

env:
- GHCVER=8.6.5 STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.6.5.yaml"
- GHCVER=8.8.3 STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.8.3.yaml"
- GHCVER=8.10.4 STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.10.4.yaml"

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - |
    if [ -z "$STACK_YAML" ]; then
      cabal v2-update
      cabal v2-build --enable-tests --enable-benchmarks
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --ghc-options='-Werror -Wno-deprecations'
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal v2-test --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false
